#!/usr/bin/env python3
import sys
import os
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WEBKIT_DIR = os.path.join(SCRIPT_DIR, "WebKit")

def run(*args, **kwargs):
    print("[run] {}".format(" ".join(*args)))
    kwargs["check"] = True
    subprocess.run(*args, **kwargs)

def main():
    if not os.path.exists(WEBKIT_DIR):
        run(["git", "clone", "https://github.com/WebKit/WebKit", WEBKIT_DIR])

main()
