pub const TagId = enum {
    a, abbr, acronym, defines, address, applet, area, article, aside, audio,
    b, base, basefont, Specifies, bdi, bdo, big, blockquote, body, br, button,
    canvas, caption, center, cite, code, col, colgroup, command,
    data, datalist, dd, del, details, dfn, dialog, dir, div, dl, dt, em, embed,
    fieldset, figcaption, figure, font, footer, form, frame, frameset,
    h1, h2, h3, h4, h5, h6, head, header, hr, html, i, iframe, img, input, ins, kbd, keygen,
    label, legend, li, link, main, map, mark, meta, meter, nav, noframes, noscript,
    object, ol, optgroup, option, output, p, param, picture, pre, progress, q,
    rp, rt, ruby, s, samp, script, section, select, small, source, span, strike,
    strong, style, sub, summary, sup, svg,
    table, tbody, td, template, textarea, tfoot, th, thead, time, title, tr, track, tt,
    u, ul, @"var", video, wbr,
};
pub const AttrId = enum {
    accept, @"accept-charset", accesskey, action, @"align", alt, as, @"async", autocomplete, autofocus, autoplay,
    bgcolor, border, charset, checked, cite, class, color, cols, colspan, content, contenteditable, controls, coords,
    data, datetime, default, @"defer", dir, dirname, disabled, download, draggable,
    enctype, @"for", form, formaction, headers, height, hidden, high, href, hreflang, @"http-equiv",
    id, ismap, kind, label, lang, list, loop, low, max, maxlength, media, method, min, multiple, muted,
    name, nomodule, novalidate, onabort, onafterprint, onbeforeprint, onbeforeunload, onblur, oncanplay,
    oncanplaythrough, onchange, onclick, oncontextmenu, oncopy, oncuechange, oncut, ondblclick,
    ondrag, ondragend, ondragenter, ondragleave, ondragover, ondragstart, ondrop, ondurationchange,
    onemptied, onended, onerror, onfocus, onhashchange, oninput, oninvalid, onkeydown, onkeypress,
    onkeyup, onload, onloadeddata, onloadedmetadata, onloadstart, onmousedown, onmousemove,
    onmouseout, onmouseover, onmouseup, onmousewheel, onoffline, ononline, onpagehide, onpageshow,
    onpaste, onpause, onplay, onplaying, onpopstate, onprogress, onratechange, onreset, onresize,
    onscroll, onsearch, onseeked, onseeking, onselect, onstalled, onstorage, onsubmit, onsuspend,
    ontimeupdate, ontoggle, onunload, onvolumechange, onwaiting, onwheel, open, optimum, pattern,
    placeholder, poster, preload, readonly, rel, required, reversed, rows, rowspan,
    sandbox, scope, selected, shape, size, sizes, span, spellcheck, src, srcdoc, srclang, srcset,
    start, step, style, tabindex, target, title, translate, type, usemap, value, width, wrap
};
