pub const TagId = enum {
    a, abbr, acronym, defines, address, applet, area, article, aside, audio,
    b, base, basefont, Specifies, bdi, bdo, big, blockquote, body, br, button,
    canvas, caption, center, cite, code, col, colgroup, command,
    data, datalist, dd, del, details, dfn, dialog, dir, div, dl, dt, em, embed,
    fieldset, figcaption, figure, font, footer, form, frame, frameset,
    h1, h2, h3, h4, h5, h6, head, header, hr, html, i, iframe, img, input, ins, kbd, keygen,
    label, legend, li, link, main, map, mark, meta, meter, nav, noframes, noscript,
    object, ol, optgroup, option, output, p, param, picture, pre, progress, q,
    rp, rt, ruby, s, samp, script, section, select, small, source, span, strike,
    strong, style, sub, summary, sup, svg,
    table, tbody, td, template, textarea, tfoot, th, thead, time, title, tr, track, tt,
    u, ul, @"var", video, wbr,

    // SVG IDs (maybe this should be its own type?)
    circle, defs, g, line, path, polygon, polyline, text, tspan, use,
};
pub const AttrId = enum {
    accept, @"accept-charset", accesskey, action, @"align", alt, as, @"async", autocomplete, autofocus, autoplay,
    bgcolor, border, charset, checked, cite, class, color, cols, colspan, content, contenteditable, controls, coords,
    data, datetime, default, @"defer", dir, dirname, disabled, download, draggable,
    enctype, @"for", form, formaction, headers, height, hidden, high, href, hreflang, @"http-equiv",
    id, ismap, kind, label, lang, list, loop, low, max, maxlength, media, method, min, multiple, muted,
    name, nomodule, novalidate, onabort, onafterprint, onbeforeprint, onbeforeunload, onblur, oncanplay,
    oncanplaythrough, onchange, onclick, oncontextmenu, oncopy, oncuechange, oncut, ondblclick,
    ondrag, ondragend, ondragenter, ondragleave, ondragover, ondragstart, ondrop, ondurationchange,
    onemptied, onended, onerror, onfocus, onhashchange, oninput, oninvalid, onkeydown, onkeypress,
    onkeyup, onload, onloadeddata, onloadedmetadata, onloadstart, onmousedown, onmousemove,
    onmouseout, onmouseover, onmouseup, onmousewheel, onoffline, ononline, onpagehide, onpageshow,
    onpaste, onpause, onplay, onplaying, onpopstate, onprogress, onratechange, onreset, onresize,
    onscroll, onsearch, onseeked, onseeking, onselect, onstalled, onstorage, onsubmit, onsuspend,
    ontimeupdate, ontoggle, onunload, onvolumechange, onwaiting, onwheel, open, optimum, pattern,
    placeholder, poster, preload, readonly, rel, required, reversed, rows, rowspan,
    sandbox, scope, selected, shape, size, sizes, span, spellcheck, src, srcdoc, srclang, srcset,
    start, step, style, tabindex, target, title, translate, type, usemap, value, width, wrap,

    // SVG IDs (maybe this should be its own type?)
    @"alignment-baseline", @"baseline-shift", clip, @"clip-path", @"clip-rule",
    @"color-interpolation", @"color-interpolation-filters", @"color-profile", @"color-rendering",
    cursor, cx, cy, d, direction, display, @"dominant-baseline", @"enable-background", fill, @"fill-opacity",
    @"fill-rule", filter, @"flood-color", @"flood-opacity", @"font-family", @"font-size", @"font-size-adjust",
    @"font-stretch", @"font-style", @"font-variant", @"font-weight", @"glyph-orientation-horizontal",
    @"glyph-orientation-vertical", @"image-rendering", kerning, @"letter-spacing", @"lighting-color",
    @"marker-end", @"marker-mid", @"marker-start", mask, opacity, overflow, @"pointer-events", points, r,
    @"shape-rendering", space, @"solid-color", @"solid-opacity", @"stop-color", @"stop-opacity", stroke,
    @"stroke-dasharray", @"stroke-dashoffset", @"stroke-linecap", @"stroke-linejoin", @"stroke-miterlimit",
    @"stroke-opacity", @"stroke-width", @"text-anchor", @"text-decoration", @"text-rendering", transform,
    @"unicode-bidi", @"vector-effect", viewBox, visibility, @"word-spacing", @"writing-mode",
    x, x1, x2, xmlns, y, y1, y2,
};
